// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount    *string    `json:"amount,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Merchant  *string    `json:"merchant,omitempty"`
	Status    *string    `json:"status,omitempty"`
}

// PaymentListResponse defines model for PaymentListResponse.
type PaymentListResponse struct {
	NextPage     *int      `json:"next_page"`
	Offset       int       `json:"offset"`
	Page         int       `json:"page"`
	PageSize     int       `json:"page_size"`
	Payments     []Payment `json:"payments"`
	PreviousPage *int      `json:"previous_page"`
	Total        int       `json:"total"`
}

// User defines model for User.
type User struct {
	Email *string `json:"email,omitempty"`
	Role  *string `json:"role,omitempty"`
	Token *string `json:"token,omitempty"`
}

// Page defines model for page.
type Page = int

// PageSize defines model for page_size.
type PageSize = int

// Search defines model for search.
type Search = string

// Sort defines model for sort.
type Sort = string

// LoginResponse defines model for LoginResponse.
type LoginResponse = User

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// PostDashboardV1AuthLoginJSONBody defines parameters for PostDashboardV1AuthLogin.
type PostDashboardV1AuthLoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetDashboardV1PaymentsParams defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParams struct {
	// Sort Comma-separated sort fields. Common patterns: `-created_at` (prefix `-` = desc) `amount` (no prefix `-` = asc)
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page 1-based page number
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Search Search by payment id, merchant, or status
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Status status of payment (completed , processing , or failed)
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// Id payment id
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// PostDashboardV1AuthLoginJSONRequestBody defines body for PostDashboardV1AuthLogin for application/json ContentType.
type PostDashboardV1AuthLoginJSONRequestBody PostDashboardV1AuthLoginJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with email + password
	// (POST /dashboard/v1/auth/login)
	PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// Logout and clear auth cookie
	// (POST /dashboard/v1/auth/logout)
	PostDashboardV1AuthLogout(w http.ResponseWriter, r *http.Request)
	// Get current authenticated user
	// (GET /dashboard/v1/auth/me)
	GetDashboardV1AuthMe(w http.ResponseWriter, r *http.Request)
	// List of payments
	// (GET /dashboard/v1/payments)
	GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login with email + password
// (POST /dashboard/v1/auth/login)
func (_ Unimplemented) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout and clear auth cookie
// (POST /dashboard/v1/auth/logout)
func (_ Unimplemented) PostDashboardV1AuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current authenticated user
// (GET /dashboard/v1/auth/me)
func (_ Unimplemented) GetDashboardV1AuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List of payments
// (GET /dashboard/v1/payments)
func (_ Unimplemented) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDashboardV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDashboardV1AuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1AuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1AuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1AuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1AuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1AuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Payments operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1PaymentsParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", r.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Payments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/auth/login", wrapper.PostDashboardV1AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/auth/logout", wrapper.PostDashboardV1AuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/auth/me", wrapper.GetDashboardV1AuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments", wrapper.GetDashboardV1Payments)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xXXW/bNhf+KwTf96LFFEtuO6AQMGDZV9AhGYJ13S6yIKGlY5uN+NFDMo0b+L8PJGVZ",
	"sijE3YpeJRYPz3me881HWimhlQRpDS0fqWbIBFjA9tcK/N8aTIVcW64kLen8ZMEM1MSfEunEApBmlPuj",
	"Dw5wQzMqmQBaxvsZNdUaBIuKlsw1lpbzjMIDE7qB8L/gkgsnwv92o/1dLi2sAOl2mwU9N4Z/SoD5Ldgn",
	"akm4BWGIBiSt2SlEUVMaVtHHVWRUsIcWWFE8CdMAw2o9xvg2fCeLDdFsI0BawuuMCMBqzaTNiEJiLLPO",
	"TIBu9fYRdyCpVXdKQ80Z7TAZi1yuIiSFdgzoRyUEOzHgo22hJl6KLDk0tZkRf6gk0cxaQGlKcntSIXi5",
	"G2ZvyTONsOQP5PbklnxHvN7n5JYJ5aQ/lIoMzpmpnv8tp3h5cGlWPZMJXtuMIhitpIGQp+dqxeXv7Rf/",
	"oVLSggzMmdYNr5hnnr83nv5jz+L/EZa0pP/L92WQx1OTvzMhrtvswHsI1qEkVt2BJEzWxBlAwuVSoQh2",
	"6DajlzHS59zYLw4spTuBsxUjXs5DeieZs2uF/BPUPyMqPAJQG5HgZRfug7ReCOqA1wnBcENLesGN4XLl",
	"c5nLe9bwOjqIZvSeNa4lXwMtXxW+4MGY0FxaVJ3WkogpTYHicR6K9BI+Od3b4kqSJeMN1N7UzmqFUHsB",
	"1hi6txf4dz7TqDSg5dEtkVUveQPBw/bQo9zP8+PZp6ob4YPj6ENxFWHsrVx38mrxHirby8kxhVi+Q2Ss",
	"4RV83/6eVUqMEWS0V6XlI40FQEtaMwsnlgtI3eH10NA8JbRrjkPRi/YrOU3daXvo4IbPjQZ8j8uIRlVB",
	"9G7ouTH4ScdOue6wnIdulPBgb/RhjF9kVLqmYQv/w6KDVHKo5dLAkG2Rkhtpn09JdfNyMM9SsoFZIBBG",
	"6JHdh+7dxBDZJuhCuOfKmc4JTxO3yrJmAPPbIjlc+7neYc52K0Z/rkeVnU+zXlwOIaaqJLT9UWxBMB5w",
	"jtIOVQPJg1i345NxfoXdoXLI7eat93I0uQCGgL5j7X/9siuxX//6Yzc6vaZ4us/ltbU69j8/lwIIbmMN",
	"bc7UOZOrU63J6eUb358BTbvZzYpZEdJRg2Sa05K+nBWzl8HBdh1Q5TUz64ViWOf389x3r7zx4ze4TJmQ",
	"w95xocG+qf0cUsb+tLv059wTCgObxqCCsT+oevNZ0/HY2GhmzEeFdToK/ZSKOno3xqkxvOIT+nAPeVEU",
	"U9XTyeXDZWWb0VfF/Olb4+Edsqabv0Er+cjtmgQq5BvSUfGS6bApZz83bv7KiParxNLrKt9tl65pNqRR",
	"q5Wfs87+V8JtmdDyalggV9fb6wN/KGfDelY1wJB4baRS6o7DlENEqOMVJHxxBoeuuACajv4XT+KJBrNN",
	"JujBou8Q/QrYbahfy/1nYEnVGh9sOAFKIgD9MXREBC77E2D/ZL1K09qL5OHNsc2elAvj4Ui5OHiOEG4f",
	"cl5yGKe4uvhX7O6F+OzpzeX51LNq95bcp9oodQ4B7B+mE0rDwbTC63/TCZPvmK/UHrixPXeb9nEBeL/L",
	"I4dNO0fLPG9UxZq1MrZ8Xbwu6PZ6+08AAAD//4DP/mc5EQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
